version: '3.9'

#networks:
#  postgres_network:
#    name: postgres_net
#    driver: local

services:
  postgres:
    image: postgres
    container_name: postgres_container
    restart: always
    environment:
      POSTGRES_HOST: postgres
      POSTGRES_PASSWORD: j3141592
      POSTGRES_USER: postgres
      POSTGRES_DB: family_restaurant_db
    ports:
      - "5432:5432"
    command: postgres
    expose:
      - 5432


  family_restaurant:
    container_name: family_restaurant_container
    build:
      context: .
      dockerfile: Dockerfile
    image: "family_restaurant"
    depends_on:
      - postgres
    environment:
      DATABASE_HOST: postgres
      DATABASE_PORT: 5432
      DATABASE_NAME: family_restaurant_db
      DATABASE_USER: postgres
      DATABASE_PASSWORD: j3141592
